import { SkillInterface } from '../types/combo';

export interface DailyPresetItem {
  id: string;
  dayOfWeek: 'MONDAY' | 'TUESDAY' | 'WEDNESDAY' | 'THURSDAY' | 'FRIDAY' | 'SATURDAY' | 'SUNDAY';
  dayIndex: number; // 0: Sun, 1: Mon, 2: Tue, 3: Wed, 4: Thu, 5: Fri, 6: Sat
  dayNameKo: string;
  dayNameEn: string;
  dayShortKo: string;
  dayShortEn: string;
  title: string;
  titleEn: string;
  description: string;
  descriptionEn: string;
  focusArea: string;
  focusAreaEn: string;
  roundTimeSeconds: number;
  restTimeSeconds: number;
  recommendedSets: number;
  tagList: string;
  colorTheme: string;
  difficultyLevel: string;
  comboItems: SkillInterface[];
}

export const DAILY_PRESETS: DailyPresetItem[] = [
  // 1. 월요일 (Monday) - 잽 & 스트레이트 기초 확립
  {
    id: 'preset-monday-fundamentals',
    dayOfWeek: 'MONDAY',
    dayIndex: 1,
    dayNameKo: '월요일',
    dayNameEn: 'Monday',
    dayShortKo: '월',
    dayShortEn: 'Mon',
    title: '월요일: 스트레이트 정석 & 기본기 마스터',
    titleEn: 'Monday: Straight & Fundamentals Master',
    description: '한 주의 시작! 잽(1)과 원투(1-2), 더블잽투(1-1-2)로 정교한 타점과 거리감을 잡는 기본기 완성 루틴.',
    descriptionEn: 'Start the week strong with crisp 1-2 jabs and straight combinations to hone your range and accuracy.',
    focusArea: '기본 잽, 원투, 더블잽 타점 확립',
    focusAreaEn: 'Jabs, One-Two Cross, Double-Jab accuracy',
    roundTimeSeconds: 180,
    restTimeSeconds: 30,
    recommendedSets: 5,
    tagList: '#월요기본기 #원투정석 #거리감잡기 #초보추천',
    colorTheme: '#38bdf8',
    difficultyLevel: 'BEGINNER',
    comboItems: [
      {
        id: '1',
        name: '1. 잽',
        nameEn: '1. Jab',
        sequence: ['1', '-', '-'],
        isPreset: true,
        isCombo: false,
        category: 'basic',
        color: '#38bdf8',
        durationMs: 1400,
        description: '왼손 잽 (1 -> - -> -)',
        descriptionEn: 'Lead jab (1 -> - -> -)',
      },
      {
        id: 'preset-one-two',
        name: '1-2 (원-투)',
        nameEn: '1-2 (One-Two)',
        sequence: ['1', '2', '-', '-'],
        tokenCount: 2,
        isPreset: true,
        isCombo: true,
        category: 'preset-combo',
        color: '#1aee5a',
        durationMs: 1800,
        description: '잽-스트레이트 2연타 (1 -> 2 -> - -> -)',
        descriptionEn: 'Jab-Cross combination (1 -> 2 -> - -> -)',
      },
      {
        id: 'preset-1-1-2',
        name: '1-1-2 (더블잽-투)',
        nameEn: '1-1-2 (Double Jab-Cross)',
        sequence: ['1', '1', '2', '-', '-'],
        tokenCount: 3,
        isPreset: true,
        isCombo: true,
        category: 'preset-combo',
        color: '#98c02b',
        durationMs: 2000,
        description: '더블 잽 후 스트레이트 (1 -> 1 -> 2 -> - -> -)',
        descriptionEn: 'Double jab followed by cross (1 -> 1 -> 2 -> - -> -)',
      },
      {
        id: 'preset-1-2-3-2',
        name: '1-2-3-2 (원-투-훅-투)',
        nameEn: '1-2-3-2 (Jab-Cross-Hook-Cross)',
        sequence: ['1', '2', '3', '2', '-', '-', '-'],
        tokenCount: 4,
        isPreset: true,
        isCombo: true,
        category: 'preset-combo',
        color: '#1529db',
        durationMs: 2600,
        description: '원투 후 왼훅-스트레이트 4연타 (1 -> 2 -> 3 -> 2 -> - -> - -> -)',
        descriptionEn: 'One-two into lead hook and rear cross',
      },
    ],
  },

  // 2. 화요일 (Tuesday) - 상체 회피 & 슬립 카운터
  {
    id: 'preset-tuesday-defense',
    dayOfWeek: 'TUESDAY',
    dayIndex: 2,
    dayNameKo: '화요일',
    dayNameEn: 'Tuesday',
    dayShortKo: '화',
    dayShortEn: 'Tue',
    title: '화요일: 더킹·위빙 회피 & 카운터 어택',
    titleEn: 'Tuesday: Duck, Weave & Counter Attack',
    description: '상대 주먹을 눈으로 보지 않고 몸으로 피한다! 슬립과 더킹, 위빙 후 곧바로 꽂아 넣는 실전 카운터 루틴.',
    descriptionEn: 'Master defensive slips and weaves under punches, immediately returning with punishing counters.',
    focusArea: '상체 유연성, 슬립 회피, 더킹 후 연타',
    focusAreaEn: 'Head movement, slip defense, counter hooks',
    roundTimeSeconds: 180,
    restTimeSeconds: 30,
    recommendedSets: 5,
    tagList: '#슬립회피 #더킹위빙 #카운터펀치 #스파링대비',
    colorTheme: '#a855f7',
    difficultyLevel: 'INTERMEDIATE',
    comboItems: [
      {
        id: 'preset-one-two',
        name: '1-2 (원-투)',
        nameEn: '1-2 (One-Two)',
        sequence: ['1', '2', '-', '-'],
        tokenCount: 2,
        isPreset: true,
        isCombo: true,
        category: 'preset-combo',
        color: '#1aee5a',
        durationMs: 1800,
        description: '잽-스트레이트 2연타 (1 -> 2 -> - -> -)',
        descriptionEn: 'Jab-Cross combination',
      },
      {
        id: 'preset-1-2-slip-2',
        name: '1-2-R슬립-2',
        nameEn: '1-2-R Slip-2',
        sequence: ['1', '2', 'r-slip', '2', '-', '-', '-'],
        tokenCount: 4,
        isPreset: true,
        isCombo: true,
        category: 'preset-combo',
        color: '#fdb01f',
        durationMs: 2600,
        description: '원투 후 우측 슬립 후 강력한 스트레이트 카운터 (1 -> 2 -> R슬립 -> 2 -> - -> - -> -)',
        descriptionEn: 'Jab-Cross, right slip, rear cross counter',
      },
      {
        id: 'preset-duck-5-4-weave',
        name: '더킹-5-4-R위빙',
        nameEn: 'Duck-5-4-R Weave',
        sequence: ['duck', '5', '4', 'r-weave', '-', '-', '-'],
        tokenCount: 4,
        isPreset: true,
        isCombo: true,
        category: 'preset-combo',
        color: '#ff2f97',
        durationMs: 2800,
        description: '더킹 회피 후 왼어퍼-오른훅 연타 및 위빙 복귀 (더킹 -> 5 -> 4 -> R위빙 -> - -> - -> -)',
        descriptionEn: 'Duck under, lead uppercut, rear hook, right weave',
      },
      {
        id: 'preset-1-2-weave-4-5',
        name: '1-2-R위빙-4-3-L위빙-3-4',
        nameEn: '1-2-R Weave-4-3-L Weave-3-4',
        sequence: ['1', '2', 'r-weave', '4', '3', 'l-weave', '3', '4', '-', '-', '-', '-'],
        tokenCount: 8,
        isPreset: true,
        isCombo: true,
        category: 'preset-combo',
        color: '#c084fc',
        durationMs: 4200,
        description: '원투-위빙-양훅-위빙-양훅 무한 난타 (1 -> 2 -> R위빙 -> 4 -> 3 -> L위빙 -> 3 -> 4 -> - -> - -> - -> -)',
        descriptionEn: 'Continuous weave and hook combination',
      },
    ],
  },

  // 3. 수요일 (Wednesday) - 인파이터 바디 블로우 & 어퍼컷
  {
    id: 'preset-wednesday-infighting',
    dayOfWeek: 'WEDNESDAY',
    dayIndex: 3,
    dayNameKo: '수요일',
    dayNameEn: 'Wednesday',
    dayShortKo: '수',
    dayShortEn: 'Wed',
    title: '수요일: 지옥의 바디샷 & 인파이팅 폭격',
    titleEn: 'Wednesday: Liver Body Shot & Infighting',
    description: '가드를 뚫고 상대 복부를 쪼개는 7번 리버샷과 턱을 올리는 5번 어퍼컷! 체력을 깎아먹는 인파이터 특화 훈련.',
    descriptionEn: 'Target the liver and ribs with powerful lead body shots (7) combined with uppercuts to break guards.',
    focusArea: '리버샷(7), 안면-복부 상하 분산 타격, 근접전',
    focusAreaEn: 'Body shots, level changes, close-range power',
    roundTimeSeconds: 180,
    restTimeSeconds: 30,
    recommendedSets: 6,
    tagList: '#인파이팅 #리버샷 #바디블로우 #복부폭격',
    colorTheme: '#f43f5e',
    difficultyLevel: 'INTERMEDIATE',
    comboItems: [
      {
        id: 'preset-1-2-7-3',
        name: '1-2-7-3 (원-투-바디-훅)',
        nameEn: '1-2-7-3 (Jab-Cross-Body-Hook)',
        sequence: ['1', '2', '7', '3', '-', '-', '-'],
        tokenCount: 4,
        isPreset: true,
        isCombo: true,
        category: 'preset-combo',
        color: '#8624b4',
        durationMs: 2600,
        description: '원투 안면 타격 후 7번 왼바디-왼훅 레벨체인지 (1 -> 2 -> 7 -> 3 -> - -> - -> -)',
        descriptionEn: 'Jab-Cross to head, left body rip, lead hook',
      },
      {
        id: 'preset-duck-5-4-weave',
        name: '더킹-5-4-R위빙',
        nameEn: 'Duck-5-4-R Weave',
        sequence: ['duck', '5', '4', 'r-weave', '-', '-', '-'],
        tokenCount: 4,
        isPreset: true,
        isCombo: true,
        category: 'preset-combo',
        color: '#ff2f97',
        durationMs: 2800,
        description: '더킹 회피 후 왼어퍼-오른훅 연타 및 위빙 복귀 (더킹 -> 5 -> 4 -> R위빙 -> - -> - -> -)',
        descriptionEn: 'Duck under, lead uppercut, rear hook, right weave',
      },
      {
        id: 'preset-1-2-3-2',
        name: '1-2-3-2 (원-투-훅-투)',
        nameEn: '1-2-3-2 (Jab-Cross-Hook-Cross)',
        sequence: ['1', '2', '3', '2', '-', '-', '-'],
        tokenCount: 4,
        isPreset: true,
        isCombo: true,
        category: 'preset-combo',
        color: '#1529db',
        durationMs: 2600,
        description: '원투 후 왼훅-스트레이트 4연타 (1 -> 2 -> 3 -> 2 -> - -> - -> -)',
        descriptionEn: 'One-two into lead hook and rear cross',
      },
      {
        id: 'preset-1-2-7-3',
        name: '1-2-7-3 (원-투-바디-훅)',
        nameEn: '1-2-7-3 (Jab-Cross-Body-Hook)',
        sequence: ['1', '2', '7', '3', '-', '-', '-'],
        tokenCount: 4,
        isPreset: true,
        isCombo: true,
        category: 'preset-combo',
        color: '#8624b4',
        durationMs: 2600,
        description: '원투 안면 타격 후 7번 왼바디-왼훅 레벨체인지 (1 -> 2 -> 7 -> 3 -> - -> - -> -)',
        descriptionEn: 'Jab-Cross to head, left body rip, lead hook',
      },
    ],
  },

  // 4. 목요일 (Thursday) - 스텝백 & 아웃복싱 거리 조절
  {
    id: 'preset-thursday-footwork',
    dayOfWeek: 'THURSDAY',
    dayIndex: 4,
    dayNameKo: '목요일',
    dayNameEn: 'Thursday',
    dayShortKo: '목',
    dayShortEn: 'Thu',
    title: '목요일: 스텝백 & 아웃복서 거리 조절',
    titleEn: 'Thursday: Step Back & Out-Boxing Distance',
    description: '맞지 않고 때린다! 원투 후 상대 반격을 백스텝으로 흘려보내고 재진입하여 꽂는 스마트한 풋워크 루틴.',
    descriptionEn: "Hit and don't get hit. Step back out of range to evade counters, then instantly explode forward.",
    focusArea: '백스텝(Back), 무게중심 이동, 거리 리셋 & 재진입',
    focusAreaEn: 'Footwork, weight transfer, resetting range',
    roundTimeSeconds: 180,
    restTimeSeconds: 30,
    recommendedSets: 5,
    tagList: '#아웃복싱 #스텝백 #거리조절 #풋워크',
    colorTheme: '#fb923c',
    difficultyLevel: 'ALL_LEVELS',
    comboItems: [
      {
        id: 'preset-1-2-back-1-2',
        name: '1-2-백-1-2',
        nameEn: '1-2-Back-1-2',
        sequence: ['1', '2', 'back', '1', '2', '-', '-', '-'],
        tokenCount: 5,
        isPreset: true,
        isCombo: true,
        category: 'preset-combo',
        color: '#c23d25',
        durationMs: 3000,
        description: '원투 진입 후 백스텝으로 거리 벌리고 재진입 원투 (1 -> 2 -> 백 -> 1 -> 2 -> - -> - -> -)',
        descriptionEn: 'Jab-Cross, step back to reset range, Jab-Cross reentry',
      },
      {
        id: 'preset-1-2-slip-2',
        name: '1-2-R슬립-2',
        nameEn: '1-2-R Slip-2',
        sequence: ['1', '2', 'r-slip', '2', '-', '-', '-'],
        tokenCount: 4,
        isPreset: true,
        isCombo: true,
        category: 'preset-combo',
        color: '#fdb01f',
        durationMs: 2600,
        description: '원투 후 우측 슬립 후 강력한 스트레이트 카운터 (1 -> 2 -> R슬립 -> 2 -> - -> - -> -)',
        descriptionEn: 'Jab-Cross, right slip, rear cross counter',
      },
      {
        id: 'preset-1-1-2',
        name: '1-1-2 (더블잽-투)',
        nameEn: '1-1-2 (Double Jab-Cross)',
        sequence: ['1', '1', '2', '-', '-'],
        tokenCount: 3,
        isPreset: true,
        isCombo: true,
        category: 'preset-combo',
        color: '#98c02b',
        durationMs: 2000,
        description: '더블 잽 후 스트레이트 (1 -> 1 -> 2 -> - -> -)',
        descriptionEn: 'Double jab followed by cross',
      },
      {
        id: 'preset-1-2-back-1-2',
        name: '1-2-백-1-2',
        nameEn: '1-2-Back-1-2',
        sequence: ['1', '2', 'back', '1', '2', '-', '-', '-'],
        tokenCount: 5,
        isPreset: true,
        isCombo: true,
        category: 'preset-combo',
        color: '#c23d25',
        durationMs: 3000,
        description: '원투 진입 후 백스텝으로 거리 벌리고 재진입 원투 (1 -> 2 -> 백 -> 1 -> 2 -> - -> - -> -)',
        descriptionEn: 'Jab-Cross, step back to reset range, Jab-Cross reentry',
      },
    ],
  },

  // 5. 금요일 (Friday) - 불금 샌드백 폭격 & 스피드 4연타
  {
    id: 'preset-friday-heavybag',
    dayOfWeek: 'FRIDAY',
    dayIndex: 5,
    dayNameKo: '금요일',
    dayNameEn: 'Friday',
    dayShortKo: '금',
    dayShortEn: 'Fri',
    title: '금요일: 불금 샌드백 폭격 & 스피드 연타',
    titleEn: 'Friday: Heavy Bag Blast & Speed Combo',
    description: '한 주의 스트레스를 샌드백에 쏟아붓는 하이템포 연타! 끊임없이 주먹을 쏟아내는 폭발적 심폐 인터벌 트레이닝.',
    descriptionEn: 'Unleash intense, high-tempo punch combinations on the heavy bag to melt stress and burn max calories.',
    focusArea: '스피드, 콤보 연타 유지력, 칼로리 버닝',
    focusAreaEn: 'Punch speed, continuous striking, high cardio',
    roundTimeSeconds: 180,
    restTimeSeconds: 30,
    recommendedSets: 6,
    tagList: '#샌드백폭격 #불금버닝 #칼로리폭탄 #연타스퍼트',
    colorTheme: '#FF2E54',
    difficultyLevel: 'ADVANCED',
    comboItems: [
      {
        id: 'preset-1-1-2',
        name: '1-1-2 (더블잽-투)',
        nameEn: '1-1-2 (Double Jab-Cross)',
        sequence: ['1', '1', '2', '-', '-'],
        tokenCount: 3,
        isPreset: true,
        isCombo: true,
        category: 'preset-combo',
        color: '#98c02b',
        durationMs: 2000,
        description: '더블 잽 후 스트레이트 (1 -> 1 -> 2 -> - -> -)',
        descriptionEn: 'Double jab followed by cross',
      },
      {
        id: 'preset-1-2-3-2',
        name: '1-2-3-2 (원-투-훅-투)',
        nameEn: '1-2-3-2 (Jab-Cross-Hook-Cross)',
        sequence: ['1', '2', '3', '2', '-', '-', '-'],
        tokenCount: 4,
        isPreset: true,
        isCombo: true,
        category: 'preset-combo',
        color: '#1529db',
        durationMs: 2600,
        description: '원투 후 왼훅-스트레이트 4연타 (1 -> 2 -> 3 -> 2 -> - -> - -> -)',
        descriptionEn: 'One-two into lead hook and rear cross',
      },
      {
        id: 'preset-1-2-7-3',
        name: '1-2-7-3 (원-투-바디-훅)',
        nameEn: '1-2-7-3 (Jab-Cross-Body-Hook)',
        sequence: ['1', '2', '7', '3', '-', '-', '-'],
        tokenCount: 4,
        isPreset: true,
        isCombo: true,
        category: 'preset-combo',
        color: '#8624b4',
        durationMs: 2600,
        description: '원투 안면 타격 후 7번 왼바디-왼훅 레벨체인지 (1 -> 2 -> 7 -> 3 -> - -> - -> -)',
        descriptionEn: 'Jab-Cross to head, left body rip, lead hook',
      },
      {
        id: 'preset-1-2-weave-4-5',
        name: '1-2-R위빙-4-3-L위빙-3-4',
        nameEn: '1-2-R Weave-4-3-L Weave-3-4',
        sequence: ['1', '2', 'r-weave', '4', '3', 'l-weave', '3', '4', '-', '-', '-', '-'],
        tokenCount: 8,
        isPreset: true,
        isCombo: true,
        category: 'preset-combo',
        color: '#c084fc',
        durationMs: 4200,
        description: '원투-위빙-양훅-위빙-양훅 무한 난타 (1 -> 2 -> R위빙 -> 4 -> 3 -> L위빙 -> 3 -> 4 -> - -> - -> - -> -)',
        descriptionEn: 'Continuous weave and hook combination',
      },
    ],
  },

  // 6. 토요일 (Saturday) - 올라운드 실전 챔피언 루틴
  {
    id: 'preset-saturday-champion',
    dayOfWeek: 'SATURDAY',
    dayIndex: 6,
    dayNameKo: '토요일',
    dayNameEn: 'Saturday',
    dayShortKo: '토',
    dayShortEn: 'Sat',
    title: '토요일: 올라운드 챔피언 실전 콤비네이션',
    titleEn: 'Saturday: All-Round Champion Routine',
    description: '공격, 슬립 회피, 바디 블로우, 백스텝까지 복싱의 모든 기술을 하나로 엮어낸 토요일 정규 스파링 대비 완성 루틴.',
    descriptionEn: 'A comprehensive championship routine integrating jabs, counters, body shots, and defensive weaves.',
    focusArea: '공수 전환 속도, 전신 콤비네이션 완성도',
    focusAreaEn: 'Transition speed, complete boxing repertoire',
    roundTimeSeconds: 180,
    restTimeSeconds: 30,
    recommendedSets: 6,
    tagList: '#챔피언루틴 #올라운드 #실전스파링 #풀패키지',
    colorTheme: '#eab308',
    difficultyLevel: 'ADVANCED',
    comboItems: [
      {
        id: 'preset-one-two',
        name: '1-2 (원-투)',
        nameEn: '1-2 (One-Two)',
        sequence: ['1', '2', '-', '-'],
        tokenCount: 2,
        isPreset: true,
        isCombo: true,
        category: 'preset-combo',
        color: '#1aee5a',
        durationMs: 1800,
        description: '잽-스트레이트 2연타 (1 -> 2 -> - -> -)',
        descriptionEn: 'Jab-Cross combination',
      },
      {
        id: 'preset-1-2-slip-2',
        name: '1-2-R슬립-2',
        nameEn: '1-2-R Slip-2',
        sequence: ['1', '2', 'r-slip', '2', '-', '-', '-'],
        tokenCount: 4,
        isPreset: true,
        isCombo: true,
        category: 'preset-combo',
        color: '#fdb01f',
        durationMs: 2600,
        description: '원투 후 우측 슬립 후 강력한 스트레이트 카운터 (1 -> 2 -> R슬립 -> 2 -> - -> - -> -)',
        descriptionEn: 'Jab-Cross, right slip, rear cross counter',
      },
      {
        id: 'preset-1-2-7-3',
        name: '1-2-7-3 (원-투-바디-훅)',
        nameEn: '1-2-7-3 (Jab-Cross-Body-Hook)',
        sequence: ['1', '2', '7', '3', '-', '-', '-'],
        tokenCount: 4,
        isPreset: true,
        isCombo: true,
        category: 'preset-combo',
        color: '#8624b4',
        durationMs: 2600,
        description: '원투 안면 타격 후 7번 왼바디-왼훅 레벨체인지 (1 -> 2 -> 7 -> 3 -> - -> - -> -)',
        descriptionEn: 'Jab-Cross to head, left body rip, lead hook',
      },
      {
        id: 'preset-1-2-back-1-2',
        name: '1-2-백-1-2',
        nameEn: '1-2-Back-1-2',
        sequence: ['1', '2', 'back', '1', '2', '-', '-', '-'],
        tokenCount: 5,
        isPreset: true,
        isCombo: true,
        category: 'preset-combo',
        color: '#c23d25',
        durationMs: 3000,
        description: '원투 진입 후 백스텝으로 거리 벌리고 재진입 원투 (1 -> 2 -> 백 -> 1 -> 2 -> - -> - -> -)',
        descriptionEn: 'Jab-Cross, step back to reset range, Jab-Cross reentry',
      },
      {
        id: 'preset-duck-5-4-weave',
        name: '더킹-5-4-R위빙',
        nameEn: 'Duck-5-4-R Weave',
        sequence: ['duck', '5', '4', 'r-weave', '-', '-', '-'],
        tokenCount: 4,
        isPreset: true,
        isCombo: true,
        category: 'preset-combo',
        color: '#ff2f97',
        durationMs: 2800,
        description: '더킹 회피 후 왼어퍼-오른훅 연타 및 위빙 복귀 (더킹 -> 5 -> 4 -> R위빙 -> - -> - -> -)',
        descriptionEn: 'Duck under, lead uppercut, rear hook, right weave',
      },
    ],
  },

  // 7. 일요일 (Sunday) - 섀도우 유산소 밸런스 & 쿨다운
  {
    id: 'preset-sunday-recovery',
    dayOfWeek: 'SUNDAY',
    dayIndex: 0,
    dayNameKo: '일요일',
    dayNameEn: 'Sunday',
    dayShortKo: '일',
    dayShortEn: 'Sun',
    title: '일요일: 섀도우 밸런스 유산소 & 쿨다운',
    titleEn: 'Sunday: Shadow Balance Cardio & Recovery',
    description: '주말을 가볍고 상쾌하게 마무리! 거울을 보며 완벽한 폼과 호흡에 집중하는 부드러운 리듬의 유산소 섀도우복싱.',
    descriptionEn: 'Refine your form and flow with light-paced shadow boxing combinations for optimal recovery.',
    focusArea: '호흡, 밸런스, 섀도우 리듬감, 유산소 땀내기',
    focusAreaEn: 'Breathing, balance, shadow rhythm, recovery',
    roundTimeSeconds: 180,
    restTimeSeconds: 30,
    recommendedSets: 4,
    tagList: '#섀도우복싱 #유산소 #주말마무리 #밸런스회복',
    colorTheme: '#34d399',
    difficultyLevel: 'ALL_LEVELS',
    comboItems: [
      {
        id: '1',
        name: '1. 잽',
        nameEn: '1. Jab',
        sequence: ['1', '-', '-'],
        isPreset: true,
        isCombo: false,
        category: 'basic',
        color: '#38bdf8',
        durationMs: 1400,
        description: '왼손 잽 (1 -> - -> -)',
        descriptionEn: 'Lead jab (1 -> - -> -)',
      },
      {
        id: 'preset-one-two',
        name: '1-2 (원-투)',
        nameEn: '1-2 (One-Two)',
        sequence: ['1', '2', '-', '-'],
        tokenCount: 2,
        isPreset: true,
        isCombo: true,
        category: 'preset-combo',
        color: '#1aee5a',
        durationMs: 1800,
        description: '잽-스트레이트 2연타 (1 -> 2 -> - -> -)',
        descriptionEn: 'Jab-Cross combination',
      },
      {
        id: 'preset-1-1-2',
        name: '1-1-2 (더블잽-투)',
        nameEn: '1-1-2 (Double Jab-Cross)',
        sequence: ['1', '1', '2', '-', '-'],
        tokenCount: 3,
        isPreset: true,
        isCombo: true,
        category: 'preset-combo',
        color: '#98c02b',
        durationMs: 2000,
        description: '더블 잽 후 스트레이트 (1 -> 1 -> 2 -> - -> -)',
        descriptionEn: 'Double jab followed by cross',
      },
      {
        id: 'preset-1-2-back-1-2',
        name: '1-2-백-1-2',
        nameEn: '1-2-Back-1-2',
        sequence: ['1', '2', 'back', '1', '2', '-', '-', '-'],
        tokenCount: 5,
        isPreset: true,
        isCombo: true,
        category: 'preset-combo',
        color: '#c23d25',
        durationMs: 3000,
        description: '원투 진입 후 백스텝으로 거리 벌리고 재진입 원투 (1 -> 2 -> 백 -> 1 -> 2 -> - -> - -> -)',
        descriptionEn: 'Jab-Cross, step back to reset range, Jab-Cross reentry',
      },
      {
        id: 'preset-1-2-3-2',
        name: '1-2-3-2 (원-투-훅-투)',
        nameEn: '1-2-3-2 (Jab-Cross-Hook-Cross)',
        sequence: ['1', '2', '3', '2', '-', '-', '-'],
        tokenCount: 4,
        isPreset: true,
        isCombo: true,
        category: 'preset-combo',
        color: '#1529db',
        durationMs: 2600,
        description: '원투 후 왼훅-스트레이트 4연타 (1 -> 2 -> 3 -> 2 -> - -> - -> -)',
        descriptionEn: 'One-two into lead hook and rear cross',
      },
    ],
  },
];

/**
 * Returns today's preset item based on user's device local timezone.
 */
export function getTodayPresetConstant(clientDate: Date = new Date()): DailyPresetItem {
  const dayIndex = clientDate.getDay(); // 0: Sun, 1: Mon, ..., 6: Sat
  const found = DAILY_PRESETS.find((p) => p.dayIndex === dayIndex);
  return found || DAILY_PRESETS[0];
}

export function getPresetByDayIndex(dayIndex: number): DailyPresetItem {
  const found = DAILY_PRESETS.find((p) => p.dayIndex === dayIndex);
  return found || DAILY_PRESETS[0];
}
